// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.tsx";
import * as $1 from "./routes/admin/image/[id].tsx";
import * as $2 from "./routes/admin/image/index.tsx";
import * as $3 from "./routes/admin/index.tsx";
import * as $4 from "./routes/admin/post/[id]/index.tsx";
import * as $5 from "./routes/admin/post/index.tsx";
import * as $6 from "./routes/api/image/[id].tsx";
import * as $7 from "./routes/api/image/index.tsx";
import * as $8 from "./routes/api/post/[id].ts";
import * as $9 from "./routes/api/post/admin.tsx";
import * as $10 from "./routes/api/post/index.ts";
import * as $11 from "./routes/auth/oauth2callback.ts";
import * as $12 from "./routes/auth/signin.ts";
import * as $13 from "./routes/auth/signout.ts";
import * as $14 from "./routes/image/[id].tsx";
import * as $15 from "./routes/image/index.tsx";
import * as $16 from "./routes/index.tsx";
import * as $17 from "./routes/new.tsx";
import * as $18 from "./routes/post/[id].tsx";
import * as $19 from "./routes/post/index.tsx";
import * as $$0 from "./islands/AdminPanel.tsx";
import * as $$1 from "./islands/ImageConvert.tsx";
import * as $$2 from "./islands/PostList.tsx";
import * as $$3 from "./islands/TextArea.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.tsx": $0,
    "./routes/admin/image/[id].tsx": $1,
    "./routes/admin/image/index.tsx": $2,
    "./routes/admin/index.tsx": $3,
    "./routes/admin/post/[id]/index.tsx": $4,
    "./routes/admin/post/index.tsx": $5,
    "./routes/api/image/[id].tsx": $6,
    "./routes/api/image/index.tsx": $7,
    "./routes/api/post/[id].ts": $8,
    "./routes/api/post/admin.tsx": $9,
    "./routes/api/post/index.ts": $10,
    "./routes/auth/oauth2callback.ts": $11,
    "./routes/auth/signin.ts": $12,
    "./routes/auth/signout.ts": $13,
    "./routes/image/[id].tsx": $14,
    "./routes/image/index.tsx": $15,
    "./routes/index.tsx": $16,
    "./routes/new.tsx": $17,
    "./routes/post/[id].tsx": $18,
    "./routes/post/index.tsx": $19,
  },
  islands: {
    "./islands/AdminPanel.tsx": $$0,
    "./islands/ImageConvert.tsx": $$1,
    "./islands/PostList.tsx": $$2,
    "./islands/TextArea.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
